import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Orange X',
  description: 'Generated by Ravena Campos',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
